export const AUTH_APPINIT = "AUTH_APPINIT";
export const AUTH_START = "AUTH_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const SEARCH_START = "SEARCH_START";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";
export const SEARCH_SUGGEST = "SEARCH_SUGGEST";
export const SEARCH_SET_ACTIVE = "SEARCH_SET_ACTIVE";
export const SEARCH_SET_SEARCHQUERY = "SEARCH_SET_SEARCHQUERY";
export const SEARCH_GO_HOME = "SEARCH_GO_HOME";

export const SELL_START = "SELL_START";
export const SELL_SUCCESS = "SELL_SUCCESS";
export const SELL_FAIL = "SELL_FAIL";
export const SELL_TAKEPREVIEW = "SELL_TAKEPREVIEW";
export const SELL_SELECTBOOK = "SELL_SELECTBOOK";
export const SELL_SET_PREVIEWSORDER = "SELL_SET_PREVIEWSORDER";
export const SELL_DELETE_PREVIEW = "SELL_DELETE_PREVIEW";
export const SELL_SET_PRICE = "SELL_SET_PRICE";
export const SELL_SET_CONDITIONS = "SELL_SET_CONDITIONS";
export const SELL_SET_DESCRIPTION = "SELL_SET_DESCRIPTION";
export const SELL_CREATEBOOK = "SELL_CREATEBOOK";

export const MSG_LISTENTOCHATS = "MSG_LISTENTOCHATS";

export const MSG_CHATUPDATE = "MSG_CHATUPDATE";
export const MSG_MESSAGESUPDATE = "MSG_MESSAGESUPDATE";

export const MSG_ADDCHAT = "MSG_ADDCHAT";
export const MSG_CONNECT = "MSG_CONNECT";
export const MSG_DISCONNECT = "MSG_DISCONNECT";
export const MSG_FAIL = "MSG_FAIL";
export const MSG_SEND = "MSG_SEND";

export const NOTIFICATIONS_SUBSCRIBE = "NOTIFICATIONS_SUBSCRIBE";
export const NOTIFICATIONS_UNSUBSCRIBE = "NOTIFICATIONS_UNSUBSCRIBE";
export const NOTIFICATIONS_UPDATE = "NOTIFICATIONS_UPDATE";
export const NOTIFICATIONS_VIEW_ITEM = "NOTIFICATIONS_VIEW_ITEM";

export const SALES_INIT = "SALES_INIT";
export const SALES_START_ACTION = "SALES_START_ACTION";
export const SALES_FAIL = "SALES_FAIL";
export const SALES_SET_FOCUS = "SALES_SET_FOCUS";
export const SALES_SET_COMPOSER = "SALES_SET_COMPOSER";
export const SALES_RECEIVE_MSG = "SALES_RECEIVE_MSG";
export const SALES_SEND_MSG = "SALES_SEND_MSG";
export const SALES_CONFIRM_MSG = "SALES_CONFIRM_MSG";
export const SALES_READ_CHAT = "SALES_READ_CHAT";
export const SALES_SETTLE_CHAT = "SALES_SETTLE_CHAT";

export const SHOPPING_INIT = "SHOPPING_INIT";
export const SHOPPING_START_ACTION = "SHOPPING_START_ACTION";
export const SHOPPING_FAIL = "SHOPPING_FAIL";
export const SHOPPING_SET_FOCUS = "SHOPPING_SET_FOCUS";
export const SHOPPING_SET_COMPOSER = "SHOPPING_SET_COMPOSER";
export const SHOPPING_RECEIVE_MSG = "SHOPPING_RECEIVE_MSG";
export const SHOPPING_SEND_MSG = "SHOPPING_SEND_MSG";
export const SHOPPING_CONFIRM_MSG = "SHOPPING_CONFIRM_MSG";
export const SHOPPING_READ_CHAT = "SHOPPING_READ_CHAT";
export const SHOPPING_SETTLE_CHAT = "SHOPPING_SETTLE_CHAT";